// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNrRC2LpCDKfR7tTVtlXDzpL0eNgqEvF8',
    appId: '1:504667552703:ios:e178f3fd5cd252bc91bf0a',
    messagingSenderId: '504667552703',
    projectId: 'cargo-delivery-app-b0f42',
    databaseURL: 'https://cargo-delivery-app-b0f42-default-rtdb.firebaseio.com',
    storageBucket: 'cargo-delivery-app-b0f42.firebasestorage.app',
    iosBundleId: 'com.example.cargo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNrRC2LpCDKfR7tTVtlXDzpL0eNgqEvF8',
    appId: '1:504667552703:ios:e178f3fd5cd252bc91bf0a',
    messagingSenderId: '504667552703',
    projectId: 'cargo-delivery-app-b0f42',
    databaseURL: 'https://cargo-delivery-app-b0f42-default-rtdb.firebaseio.com',
    storageBucket: 'cargo-delivery-app-b0f42.firebasestorage.app',
    iosBundleId: 'com.example.cargo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6EK8U-iwDtUgSOldpj-MoL8IftIvaMU',
    appId: '1:504667552703:web:1071b01af3bb363991bf0a',
    messagingSenderId: '504667552703',
    projectId: 'cargo-delivery-app-b0f42',
    authDomain: 'cargo-delivery-app-b0f42.firebaseapp.com',
    databaseURL: 'https://cargo-delivery-app-b0f42-default-rtdb.firebaseio.com',
    storageBucket: 'cargo-delivery-app-b0f42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkTbW5b-de-uzcAMOC3SWJBUgTcJ5O50',
    appId: '1:504667552703:android:18afcba538a7648c91bf0a',
    messagingSenderId: '504667552703',
    projectId: 'cargo-delivery-app-b0f42',
    databaseURL: 'https://cargo-delivery-app-b0f42-default-rtdb.firebaseio.com',
    storageBucket: 'cargo-delivery-app-b0f42.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw6EK8U-iwDtUgSOldpj-MoL8IftIvaMU',
    appId: '1:504667552703:web:35345f4e4d34637291bf0a',
    messagingSenderId: '504667552703',
    projectId: 'cargo-delivery-app-b0f42',
    authDomain: 'cargo-delivery-app-b0f42.firebaseapp.com',
    databaseURL: 'https://cargo-delivery-app-b0f42-default-rtdb.firebaseio.com',
    storageBucket: 'cargo-delivery-app-b0f42.firebasestorage.app',
  );

}