// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfbTHpRLbh6cpKKgKujQ5EnmQ7m6qGP78',
    appId: '1:497593435460:ios:33899c61e641df56850311',
    messagingSenderId: '497593435460',
    projectId: 'gothong-congestion-management',
    databaseURL: 'https://gothong-congestion-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gothong-congestion-management.firebasestorage.app',
    iosBundleId: 'com.example.cargo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfbTHpRLbh6cpKKgKujQ5EnmQ7m6qGP78',
    appId: '1:497593435460:ios:33899c61e641df56850311',
    messagingSenderId: '497593435460',
    projectId: 'gothong-congestion-management',
    databaseURL: 'https://gothong-congestion-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gothong-congestion-management.firebasestorage.app',
    iosBundleId: 'com.example.cargo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvRzxZwAIrFh8tjr6HRFSje5uv97jvIOk',
    appId: '1:497593435460:web:d6732ca4debf182c850311',
    messagingSenderId: '497593435460',
    projectId: 'gothong-congestion-management',
    authDomain: 'gothong-congestion-management.firebaseapp.com',
    databaseURL: 'https://gothong-congestion-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gothong-congestion-management.firebasestorage.app',
    measurementId: 'G-M65NW3R15Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbwlf_83WPz202PTyCZmGCWMyU-YrK2UY',
    appId: '1:497593435460:android:eec4c28e83a95d25850311',
    messagingSenderId: '497593435460',
    projectId: 'gothong-congestion-management',
    databaseURL: 'https://gothong-congestion-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gothong-congestion-management.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvRzxZwAIrFh8tjr6HRFSje5uv97jvIOk',
    appId: '1:497593435460:web:43a47c410f4a9121850311',
    messagingSenderId: '497593435460',
    projectId: 'gothong-congestion-management',
    authDomain: 'gothong-congestion-management.firebaseapp.com',
    databaseURL: 'https://gothong-congestion-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gothong-congestion-management.firebasestorage.app',
    measurementId: 'G-5HZQEH0YD9',
  );

}